import { useFontImpoter } from "@/lib/utils";
import "./globals.css";
import type { Metadata } from "next";
import Provider from "@/components/auth/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = useFontImpoter();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${font.variable}  bg-gray-200`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
